name: iris-feature-and-prediction-pipelines

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '11 11 * * *'

env:
  PYTHON_VERSION: 3.9

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute python workflows from bash script
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
        run: |
          chmod +x ./src/run-feature-and-prediction-pipelines.sh
          ./src/run-feature-and-prediction-pipelines.sh
